### ISSUE TITLE
Local instance of Alexa Web

### ISSUE THREAD

**Issue by tangowhisky37** [sammachin/alexaweb#14]
Sam,

Thanks a ton for putting this together. The last few days I've been playing around with the Alex Java client and finally happened to stumble onto your web client.

I am trying to deploy the web client on my RasPi but i can't seem to get it to work. The Raspi is hosted at 192.168.1.13 and I've added the following URLs to the device configuration. 

> Allowed Origins  
> Your website origin, when using Login with Amazon.  
> http://localhost:5000
> http://192.168.1.13:5000
> 
> Allowed Return URLs  
> If you make HTTPs calls to Login with Amazon with redirect_uris, specify them here.  
> http://localhost:5000/code
> http://192.168.1.13:5000/code

I've also installed Redis on the RasPI and configured credspi as - 
# Alexa

Security_Profile_Description ="tangowhisky37web"
Security_Profile_ID  = "xxx"
Client_ID = "xxxx"
Client_Secret = "xxx"
# Redis

redis_url = "127.0.0.1:6379"

I get to the screen where I am asked by Amazon if i want to authorize my device and I say yes. On the next page I see an error - 

"We're sorry! An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.
 Go to Amazon.com's Home Page"

I can't get any debug messages to show up on the code either. I wish I had better Python skills but as you've guessed I don't. Am trying to work out where the code is falling over and what is it that I might have over looked.

Any pointers would be appreciated Sam.

**Comment by jacobajit** [comment]
Don't know if this is the issue but did you replace the productID in app.py with your own?

**Comment by sammachin** [comment]
Hi @tangowhisky37 like @jacobajit said its most likely one of the parameters doesn't quite match with whats set as Amazon, often the Security Profile Description, they're very picky about it and don't provide the best error messages. I suggest triple checking your AVS credentials and possibly even creating a new profile.

**Comment by tangowhisky37** [comment]
Thanks Ajit/Sam. The Amazon Security profile seems to be right, i have got it working with the sample Amazon Java client but it quite clunky which is the reason why I am trying to sort out the Python Web UI.

Ajit - Thanks a ton, I completely missed the Product ID thingy in app.py. I am going to fix this and give it another try...:)

**Comment by tangowhisky37** [comment]
Sam - I am still trying to get my head around the basics of Python so that i can at some point fork the code and work on it. But given my poor development skills that might be some light years away...:)

Any plans on extending the capability in Alexaweb and enhancing the current UI?

**Comment by tangowhisky37** [comment]
Ajit - You were spot on mate. It was the missing product id in app.py. Thank you buddy!!!

Sam - I think you might want to add some guidelines in the readme for editing the product id. I think because i followed the Amazon tutorial first i had everything setup including the product ID. Else i would have been struggling to work out how to create a product ID...:)

Secondly, i tried the app and it seems to work on firefox but not on chrome. Have you tested it on any Andriod devices?

**Comment by sammachin** [comment]
@tangowhisky37 Yeah the setup is a little tricky, the main project I'm working on is the AlexaPi one and thats got a cleaner setup script most people are using that.

In terms of the Chrome issues, are you using https? Chrome made a change to only allow getUserMedia on trusted origins recently which could well be your issue.

**Comment by tangowhisky37** [comment]
Aaah, that might explain the issue i am having with chrome. I'll test it out first thing tomorrow morning. 

Thanks for all the support mate. Really appreciate the hard work you've put into getting this up and running.

Your web client is the only one out there. It would be great to see this evolve in something bigger.
