### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by idav-lifesuppot** [sammachin/alexaweb#15]
Using the clone method, deployed alexa web to a heroku.  It comes up but when attempting to login through amazon I get a redirect error and the url doesn't appear to be https.  I am new to heroku so I can certainly be missing something.

Thanks for the great scripts.

**Comment by jacobajit** [comment]
If you have everything else right, try replacing every "self.request.protocol" with "https." Heroku's routing can be weird otherwise. Then just make sure you have the appropriate URL in your whitelist for AVS.

**Comment by idav-lifesuppot** [comment]
Thanks I will give that a shot.

**Comment by idav-lifesuppot** [comment]
Made the changes to self.request.protocol to "https" but it doesn't seem to change when I deploy to heroku as a fresh app.

When I input the "s" into the wrong url it brings up Amazon login screen but then doesn't redirect out of amazon.

**Comment by idav-lifesuppot** [comment]
I confirmed that the changes are not being made when trying to publish app changes to heroku.

**Comment by idav-lifesuppot** [comment]
Is it usually the case to run http by default?  I notice the examples say localhost:5000 should be https, amazon isn't allowing entering whitelist urls without https.

**Comment by idav-lifesuppot** [comment]
I appreciate the help,got passed the https issue once I found how to update the heroku app. As sugested adjusting the self.request.protocol.

Still getting the error once the amazon user logs lin.  Clicking ok when in https://www.amazon.com/ap/oa, stays and doesn't redirect as specified in the beginning.  Any  ideas where that is coming from is appreciated.

**Comment by blackshroud** [comment]
I am getting the same issue when forking and setting up the heroku app (on heroku.com) after selecting the allow screen after logging in.

Any thoughts?

**Comment by blackshroud** [comment]
Hey idavalos, i worked out my issue (could be yours too)

I had deployed redis, but had not set the redis URL in the ceds.py file

Also, I had not update the ProductID in the app.py (this needs to be the name of your AWS app)

Hope this helps

**Comment by idav-lifesuppot** [comment]
Hello blackshroud,  thanks a ton for the suggestion.

I had the redis correct I think.

Made the ProductID update in app.py and that did the trick using the Application Type Id.

**Comment by blackshroud** [comment]
Glad I could help ;)

Hey idavalos, I am having the same redirect issue you were, can you clarify where you updated the "self.request.protocol" and what you changed it to?

**Comment by idav-lifesuppot** [comment]
Changed code in app.py in two places
path = self.request.protocol + "://" + self.request.host
changed to
path = "https" + "://" + self.requested.host

However making the changes required updating the heroku app.
Ran the following on the linux server after making the changes.

sudo git add .
sudo git commit -am "make it bettter"
sudo git push heroku master

Hope that helps.

**Comment by blackshroud** [comment]
Thanks mate, that solved my issue.

Think issue I think can resolved, yeah idavalos?

**Comment by idav-lifesuppot** [comment]
Yes this issue can be closed as solved.
