### ISSUE TITLE
Change locale

### ISSUE THREAD

**Issue by ToSa27** [sammachin/alexaweb#19]
Feature Request: 
I started playing around with the Alexa API recently now that Echo and Dot are announced for  Germany and the UK. As I'm debugging a multi language Alexa Skills, it would be extremely cool if there would be a way to switch language on the webpage.

**Comment by sammachin** [comment]
Right now the AVS API (which this uses) only supports US English I'm afraid. The multi language support is only in the Echo and Dot, not even the TAP yet.
