### ISSUE TITLE
Error on line app.py line 75

### ISSUE THREAD

**Issue by Serg4554** [sammachin/alexaweb#5]
Missing a slash "/" that makes you to have an internal error 500 (because the return path isn't correct)

It should be:

``` python
callback = path+"/code"
```

Best regards!

**Comment by hpduong** [comment]
Hi Serg4554, thanks for this.  I changed the line like you said, but still getting an 500 error.  Did you change the spacing in Line 63 at all?  Does it matter?

Line 63 callback = path + "/code"
Line 75 callback = path+"/code"

Also, what should be entered into redis_url in app.py?  Where do I find that?   

#Redis 
redis_url = ""

Thanks in advance!

**Comment by Serg4554** [comment]
Hi Hpduong, no I didn't change it but should not matter.

About the redis_url, I entered: "redis://localhost:6379". Of course, you should previously install and run Redis.

Good luck!

**Comment by sammachin** [comment]
fixed
