### ISSUE TITLE
What is the redis_url???

### ISSUE THREAD

**Issue by CyberGT** [sammachin/alexaweb#6]
Hi...
You don't tell what should we put in the redis_url in the creds.py
I've try http://localhost   and http://localhost:6379 but this not working.

when I'm tryin to connect I've an error after the amazon login.

ps:I don't use heroku but a vm with debian jessie.

**Comment by hpduong** [comment]
I am having the same issue.. I don't know what the redis_url="" should be in  creds.py.  Any help would be appreciated!  I'm running on heroku but can't login.  500: Internal Server Error

**Comment by hpduong** [comment]
I found the redis_url on the Heroku install.  

Install the redis addon in Heroku, then click on the addon to open the details page.  Once you are there, click on the settings link.  Under Connection Settings you will see:

Host
Port
Password
URL

Click "Show" next to URL and you can paste that into the creds.py file. Paste it with the "redis://" included. 

Works for me now! Good luck!

**Comment by CyberGT** [comment]
Hi,

Thx for your advice ;) and I'm happy for you but I don't use heroku, I'm
using a VM with debian jessie.

I have succeded to make alexaweb running once but few hours after that,
without changing anythings, she's not working anymore (error 500).

the one thing I've made is to add an "/ " in the path lines in the app.py

regards

2016-02-04 21:42 GMT+01:00 hpduong notifications@github.com:

**Comment by hpduong** [comment]
Ah, sorry.  Serg4554 told me he used "redis://localhost:6379" in the other thread.  

Not sure if that's helpful for you, though.

**Comment by CyberGT** [comment]
OK thx, I will try that as soon as possible.

2016-02-05 1:01 GMT+01:00 hpduong notifications@github.com:

**Comment by sammachin** [comment]
It will depend where you install redis, I'm running on heroku so its using an os env variable but it should work fine on localhost:6379 if thats where you've got it installed.
