### ISSUE TITLE
How To Implement it Without Getting Logged in

### ISSUE THREAD

**Issue by aman-saggu-git** [sammachin/alexaweb#9]
Can We edit it by passing Clientid and client_secret in code instead getting logged for user every time . Please confirm me about this

**Comment by LetMyPeopleCode** [comment]
The client ID and client secret are related to the app, not the user. As I understand it, for the app to access the service, it requires a user authentication with an Amazon account.

**Comment by sammachin** [comment]
Yep the security credentials are for the Amazon oAuth process which then needs an individual user to auth their amazon account, if you don't click the X to logout then it should set a cookie on your browser which would stay logged in.
